env:
  - CGO_ENABLED=0

before:
  hooks:
    - make clean
    - go generate ./...
    - go mod tidy
    - go mod download

builds:
  -
    goos:
      - linux
      - darwin
      - windows
      - freebsd

    goarch:
      - amd64
      - arm64
      - arm
      - ppc64le
      - s390x

    goarm:
      - 7

    ignore:
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: s390x
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: ppc64le
      - goos: windows
        goarch: s390x
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: ppc64le
      - goos: freebsd
        goarch: s390x

    flags:
      - -tags=kqueue
      - -trimpath

    ldflags:
      - "-s -w -X github.com/minio/mc/cmd.Version={{.Version}} -X github.com/minio/mc/cmd.ReleaseTag={{.Tag}} -X github.com/minio/mc/cmd.CommitID={{.FullCommit}} -X github.com/minio/mc/cmd.ShortCommitID={{.ShortCommit}}"

archives:
  -
    format: binary
    name_template: "{{ .Binary }}-release/{{ .Os }}-{{ .Arch }}/{{ .Binary }}.{{ .Version }}"

nfpms:
  -
    id: minio
    package_name: mc
    vendor: MinIO, Inc.
    homepage: https://min.io/
    maintainer: dev@min.io
    description: MinIO Client (mc) provides a modern alternative to UNIX commands like ls, cat, cp, mirror, diff, find etc. It supports filesystems and Amazon S3 compatible cloud storage service (AWS Signature v2 and v4).
    license: Apache 2.0
    bindir: /usr/bin
    formats:
      - deb
      - rpm
checksum:
  algorithm: sha256


changelog:
  sort: asc
  filters:
    exclude:
      - '^Update yaml files'

